### ISSUE TITLE
For the indices of the pieces in the String[][] board, are we assuming that the index corresponds to the normal location in chess (where row one is the bottom left corner)?

### ISSUE THREAD

**Issue by alliyfrauenpreis** [sukritchhabra/chessGame-cs451#20]
This would mean that the top row of the board is row 8

**Comment by sukritchhabra** [comment]
Nope, the bottom row is row 8. It kind of has to be that way, since the html has to be structured as we would see it, and going .through the table (towards the bottom of the table) the index would increase.

**Comment by alliyfrauenpreis** [comment]
Gotcha.
